### Daniel Austin Week 5 Homework
<span style='color:Green'>1. "Panel data" or "Python data analysis" </span>

<span style='background :blue'> 2. Series and Dataframes </span> 

## 3. Data cleansing, data fill, merges and joins, data visualization

<span style='font-family:Helvetica'> 4. inplace  </span>

<b>5. Comma Separated Values  </b>

<u>6. Null values </u>

In [1]:
import numpy as np
A = np.arange(2, 3, 2)

In [12]:
import numpy as np
arr1 = np.linspace(0, 20, num=6)
print(arr1)

import copy
arr2 = copy.deepcopy(arr1)
print(arr2)

[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


In [18]:
import numpy as np

arr1 = ([[25, 16]])
arr2 = ([[11, 2], [13, 4]])
arr3 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arr1, arr2, arr3), axis=0, out=None, dtype=None, casting = "same_kind")
print(newArray)

print("........")

sortedArray = np.sort(newArray)
print(sortedArray)



[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
........
[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [31]:
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

newArray1 = np.concatenate((one, two, three), axis=0, out=None, dtype=None, casting = "same_kind")
comboArray =np.sort(newArray1)
print(comboArray)

print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:13])
print(comboArray[-6:])
print(comboArray[:-10])
print(comboArray[-8:])
print(comboArray[-1:])









[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 21 22 23 24 25 26 27]
[27]


In [35]:
import numpy as np
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name= 'Ingredients')
quantity = pd.Series([4, 1, 2, 1], name= 'Quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name= 'Unit')

recipe = pd.concat([ingredients, quantity, unit], axis=1)
print(recipe)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [40]:
df = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    })
print(df)

desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
df = df.assign(Desserts=desserts)
print(df)

df.sort_values(by = ['Name', 'address'], inplace= True)
print(df)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  
      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot        

In [43]:
df1 = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df1.to_csv('cows_and_goats.csv')

df1 = pd.read_csv('cows_and_goats.csv')
print(df1)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [46]:
veggies = pd.DataFrame({'broccoli': [23, 109], 'radishes': [67, 310]}, index=['small farm', 'big farm'])
veggies.to_csv('veggies.csv')

veggies = pd.read_csv('veggies.csv')
print(veggies)

   Unnamed: 0  broccoli  radishes
0  small farm        23        67
1    big farm       109       310
